<a href="https://colab.research.google.com/github/lauravazqx/Analisis-Numerico/blob/main/Proyecto_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyecto 2. Análisis Numérico.
## Solución a Sistemas de Ecuaciones Lineales.
##2025-1
### Laura T. Salvador Vázquez
### Luis Galicia Luna


In [ ]:
pip install numpy scipy

In [ ]:
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve

# 18.-
Dado el sistema $Ax=b:$

(a) Resolver con eliminación Gaussiana para


$A=\begin{equation}
\begin{bmatrix}
2 & 4 & -2\\
4 & 9 & -3\\
-2 & -1 & 7
\end{bmatrix}
\end{equation}$;

$b=\begin{equation}
\begin{bmatrix}
2\\
8\\
10
\end{bmatrix}
\end{equation}$

(b) Usar factorización $LU$ de $A$ para resolver el sistema $Ay=c$, donde:

$c=\begin{equation}
\begin{bmatrix}
4\\
8\\
-6
\end{bmatrix}
\end{equation}$

In [ ]:
# Solución para el inciso 18.-(a)

# Definimos la matriz A y el vector columna b
A = np.array([[2, 4, -2],
              [4, 9, -3],
              [-2, -1, 7]])

b = np.array([2, 8, 10])

# Resolver el sistema Ax = b con eliminación Gaussiana
x = np.linalg.solve(A, b)

# Mostrar la solución
print("La solución del sistema es:")
print(x)

La solución del sistema es:
[-7.  4.  0.]


In [ ]:
# Solución para el inciso 18.-(b)

# Definimos la matriz A y el vector columna c
A = np.array([[2, 4, -2],
              [4, 9, -3],
              [-2, -1, 7]], dtype=float)

c = np.array([4, 8, -6], dtype=float)

# Dimensiones de A
n = A.shape[0]

# Inicializar L y U
L = np.zeros((n, n))
U = np.zeros((n, n))

# Factorización LU
for i in range(n):
    # U es la parte superior
    for j in range(i, n):
        U[i, j] = A[i, j]
        for k in range(i):
            U[i, j] -= L[i, k] * U[k, j]

    # L es la parte inferior
    for j in range(i, n):
        if i == j:
            L[i, i] = 1  # Diagonal de L es 1
        else:
            L[j, i] = A[j, i]
            for k in range(i):
                L[j, i] -= L[j, k] * U[k, i]
            L[j, i] /= U[i, i]

# Ahora L y U están definidas
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

# Resolver Ly = c
y = np.zeros(n)
for i in range(n):
    y[i] = c[i]
    for j in range(i):
        y[i] -= L[i, j] * y[j]

# Resolver Ux = y
x = np.zeros(n)
for i in reversed(range(n)):
    x[i] = y[i]
    for j in range(i + 1, n):
        x[i] -= U[i, j] * x[j]
    x[i] /= U[i, i]

# Mostrar la solución
print("\nLa solución del sistema Ax = c es:")
print(x)

Matriz L:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  3.  1.]]

Matriz U:
[[ 2.  4. -2.]
 [ 0.  1.  1.]
 [ 0.  0.  2.]]

La solución del sistema Ax = c es:
[-1.  1. -1.]


# 19.-
Sean $A$ y $b$ dados como sigue:

(a)

$A=\begin{equation}
\begin{bmatrix}
4 & -1 & 3\\
-8 & 4 & -7\\
12 & 1 & 8
\end{bmatrix}
\end{equation}$;
$\bar{b}=\begin{equation}
\begin{bmatrix}
-8\\
19\\
-19
\end{bmatrix}
\end{equation}$

(b)

$A=\begin{equation}
\begin{bmatrix}
1 & 4 & -2 & 1\\
-2 & -4 & -3 & 1\\
1 & 16 & -17 & 9\\
2 & 4 & -9 & -3
\end{bmatrix}
\end{equation}$;
$\bar{b}=\begin{equation}
\begin{bmatrix}
3.5\\
-2.5\\
15\\
10.5
\end{bmatrix}
\end{equation}$

(c)

$A=\begin{equation}
\begin{bmatrix}
4 & 5 & -1 & 2 & 3\\
12 & 13 & 0 & 10 & 3\\
-8 & -8 & 5 & -11 & 4\\
16 & 18 & -7 & 20 & 4\\
-4 & -9 & 31 & -31 & -1
\end{bmatrix}
\end{equation}$;
$\bar{b}=\begin{equation}
\begin{bmatrix}
34\\
93\\
-33\\
131\\
-58
\end{bmatrix}
\end{equation}$

Resolver cada sistema $Ax=\bar{b}$ con las rutinas:

* Factorización $LU.$
* Factorización $LU$ con pivoteo parcial.
* Factorización $LU$ con pivoteo total.

Comparar ressultados.

In [ ]:
# Solución para la pregunta 19

def solve_system(A, b):
    print("Resolviendo el sistema Ax = b...")

    # Factorización LU Sin pivoteo
    P, L, U = lu(A)  # Factoriza
    y = np.linalg.solve(L, b)  # Resolvemos Ly = b
    x_lu = np.linalg.solve(U, y)  # Resolvemos Ux = y

    # Factorización LU Con Pivoteo parcial
    lu_piv = lu_factor(A)  # Factoriza
    x_lu_piv = lu_solve(lu_piv, b)  # Resolvemos Ax = b con LU

    # Factorización LU Con Pivoteo total
    P, L, U = lu(A)  # Factoriza
    b_permuted = np.dot(P, b)  # Permutamos b
    y_total = np.linalg.solve(L, b_permuted)  # Resolvemos Ly = b_permuted
    x_lu_total = np.linalg.solve(U, y_total)  # Resolvemos Ux = y_total

    # Resultados obtenidos
    print("Resultados:")
    print("LU sin pivote:", x_lu)
    print("LU con pivoteo parcial:", x_lu_piv)
    print("LU con pivoteo total:", x_lu_total)
    print("\n" + "="*50 + "\n")


# Definimos los sistemas A y b
systems = [
    (np.array([[4, -1, 3],
                [-8, 4, -7],
                [12, 1, 8]], dtype=float),
     np.array([-8, 19, -19], dtype=float)),

    (np.array([[1, 4, -2, 1],
                [-2, -4, -3, 1],
                [1, 16, -17, 9],
                [2, 4, -9, -3]], dtype=float),
     np.array([3.5, -2.5, 15, 10.5], dtype=float)),

    (np.array([[4, 5, -1, 2, 3],
                [12, 13, 0, 10, 3],
                [-8, -8, 5, -11, 4],
                [16, 18, -7, 20, 4],
                [-4, -9, 31, -31, -1]], dtype=float),
     np.array([34, 93, -33, 131, -58], dtype=float))
]

# Resolver cada sistema
for A, b in systems:
    solve_system(A, b)


Resolviendo el sistema Ax = b...
Resultados:
LU sin pivote: [-61.5  34.   87. ]
LU con pivoteo parcial: [-1.  1. -1.]
LU con pivoteo total: [-1.  1. -1.]


Resolviendo el sistema Ax = b...
Resultados:
LU sin pivote: [103.14583333 -36.80729167  -7.97916667  38.625     ]
LU con pivoteo parcial: [-0.5  1.  -0.5 -1. ]
LU con pivoteo total: [160.58333333 -58.22916667 -11.41666667  64.5       ]


Resolviendo el sistema Ax = b...
Resultados:
LU sin pivote: [ 507.05104167 -425.5375     -139.90833333  -87.65         88.625     ]
LU con pivoteo parcial: [1. 2. 3. 4. 5.]
LU con pivoteo total: [1. 2. 3. 4. 5.]




### Comparación de los resultados:
* Sistema 1.

Los resultados de LU con pivoteo parcial y total son idénticos, por lo que podríamos pensar que es una técnica estable.
La solución sin pivoteo difiere tanto, que estría indicando justo lo contrario.

* Sistema 2.

Los tres métodos dan soluciones diferentes, entonces vemos que la matriz tiene problemas de estabilidad numérica.
Las diferencias son significativamente grandes, lo que observamos que los métodos están lidiando con una matriz mal condicionada o que tiene un rango reducido.

* Sistema 3.

Igual que en el primer caso, los resultados con pivoteo parcial y total son idénticos, lo que es un buen indicativo de consistencia y/o estabilidad.
La solución sin pivoteo es muy distinta de las de pivoteo, por lo que vemos que esta matriz también presenta problemas de estabilidad.

* En conclusión:

Estabilidad Numérica: Los métodos de factorización $LU$
con pivoteo parcial y total tienden a ser más estables y nos dan soluciones más confiables en sistemas con matrices que pueden ser mal condicionadas o tener propiedades numéricas desfavorables.

Variabilidad de Resultados: La diferencia en los resultados para el pivoteo parcial y total en el primer y tercer sistema, en comparación con los resultados sin pivoteo, refuerza la importancia del pivoteo para obtener soluciones precisas.

Rango de Soluciones: En el segundo sistema, las soluciones varían significativamente, lo que puede ser un indicativo de que la matriz tiene un rango reducido o está mal condicionada.


# 20.-
Dada la matriz

$A=\begin{equation}
\begin{pmatrix}
1 & 0 & 0 & 0 & 1\\
-1 & 1 & 0 & 0 & 1\\
-1 & -1 & 1 & 0 & 1\\
-1 & -1 & -1 & 1 & 1\\
-1 & -1 & -1 & -1 & 1
\end{pmatrix}
\end{equation}$

(a) ¿Qué sucede cuando se usa Eliminación Gaussiana con pivoteo parcia?

(b) Usar Eliminación Gaussiana con pivoteo parcial para resolver sistemas de varios tamaños (al menos 5) con vectores $b$ elegidos por cualquier criterio. Describir como se comporta la condición de la matriz.

(c) Escribir una rutina que factorice la matriz ($LU$) con pivoteo total.

In [ ]:
# Solución para la pregunta 20

import numpy as np
from scipy.linalg import lu_factor, lu_solve

# Definimos la matriz A
A = np.array([[1, 0, 0, 0, 1],
              [-1, 1, 0, 0, 1],
              [-1, -1, 1, 0, 1],
              [-1, -1, -1, 1, 1],
              [-1, -1, -1, -1, 1]], dtype=float)

# (a) Eliminación Gaussiana con pivoteo parcial
def gaussian_elimination_with_partial_pivoting(A):
    n = A.shape[0]
    for k in range(n):
        # Pivoteo parcial
        max_index = np.argmax(np.abs(A[k:, k])) + k
        if A[max_index, k] == 0:
            raise ValueError("La matriz es singular.")

        # Intercambiar filas
        A[[k, max_index]] = A[[max_index, k]]

        # Eliminación
        for i in range(k + 1, n):
            factor = A[i, k] / A[k, k]
            A[i, k:] -= factor * A[k, k:]

    print("Matriz A después de la eliminación Gaussiana con pivoteo parcial:")
    print(A)
    print("\n")

# Ejecutamos la eliminación Gaussiana con pivoteo parcial
gaussian_elimination_with_partial_pivoting(A.copy())

# (b) Resolver sistemas de varios tamaños
def solve_systems_with_various_sizes(A):
    print("Resolviendo sistemas de varios tamaños...")
    sizes = [2, 3, 4, 5]  # Tamaños de los sistemas (5 como máximo, ya que A es 5x5)
    for size in sizes:
        A_size = A[:size, :size]  # Tomar una submatriz de A
        b = np.random.randint(-10, 10, size=(size, 1))  # Vector b aleatorio
        print(f"Tamaño del sistema: {size}")
        print("Matriz A:")
        print(A_size)
        print("Vector b:")
        print(b)

        # Condición de la matriz
        cond_number = np.linalg.cond(A_size)
        print(f"Número de condición de A: {cond_number}")

        # Resolver el sistema
        try:
            lu_piv = lu_factor(A_size)
            x = lu_solve(lu_piv, b)
            print("Solución del sistema Ax = b:")
            print(x)
        except Exception as e:
            print(f"Error al resolver el sistema: {e}")

        print("\n" + "="*50 + "\n")

# Ejecutamos la resolución de sistemas
solve_systems_with_various_sizes(A)

# (c) Factorización LU con pivoteo total
def lu_factorization_with_total_pivoting(A):
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()
    P = np.eye(n)

    for k in range(n):
        # Pivoteo total
        max_index = np.unravel_index(np.argmax(np.abs(U[k:, k:])), U[k:, k:].shape)
        max_index = (max_index[0] + k, max_index[1] + k)

        if U[max_index] == 0:
            raise ValueError("La matriz es singular.")

        # Intercambiar filas en U
        U[[k, max_index[0]]] = U[[max_index[0], k]]
        # Intercambiar filas en P
        P[[k, max_index[0]]] = P[[max_index[0], k]]

        if max_index[0] != k:
            L[[k, max_index[0]], :k] = L[[max_index[0], k], :k]  # Intercambiar filas en L

        for i in range(k + 1, n):
            factor = U[i, k] / U[k, k]
            U[i, k:] -= factor * U[k, k:]
            L[i, k] = factor

    print("Matriz L:")
    print(L)
    print("Matriz U:")
    print(U)
    print("Matriz de permutación P:")
    print(P)

# Ejecutamos la factorización LU con pivoteo total
lu_factorization_with_total_pivoting(A.copy())


Matriz A después de la eliminación Gaussiana con pivoteo parcial:
[[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  4.]
 [ 0.  0.  0.  1.  8.]
 [ 0.  0.  0.  0. 16.]]


Resolviendo sistemas de varios tamaños...
Tamaño del sistema: 2
Matriz A:
[[ 1.  0.]
 [-1.  1.]]
Vector b:
[[ 2]
 [-2]]
Número de condición de A: 2.6180339887498953
Solución del sistema Ax = b:
[[2.]
 [0.]]


Tamaño del sistema: 3
Matriz A:
[[ 1.  0.  0.]
 [-1.  1.  0.]
 [-1. -1.  1.]]
Vector b:
[[-9]
 [-6]
 [-6]]
Número de condición de A: 5.411474127809774
Solución del sistema Ax = b:
[[ -9.]
 [-15.]
 [-30.]]


Tamaño del sistema: 4
Matriz A:
[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [-1. -1.  1.  0.]
 [-1. -1. -1.  1.]]
Vector b:
[[ -7]
 [-10]
 [-10]
 [ -7]]
Número de condición de A: 12.390625483218937
Solución del sistema Ax = b:
[[ -7.]
 [-17.]
 [-34.]
 [-65.]]


Tamaño del sistema: 5
Matriz A:
[[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  

### Respuestas teóricas.

(a) ¿Qué sucede cuando se usa Eliminación Gaussiana con pivoteo parcial?

Como es un método para resolver sistemas de ecuaciones lineales e implica transformar la matriz del sistema en una forma escalonada para que se puedan aplicar sustituciones hacia atrás para encontrar las soluciones, lo que hace el pivoteo parcial es mejorar la estabilidad numérica. Y para ello, el pivoteo parcial busca en cada paso de la eliminación el valor máximo en la columna de pivote a partir de la fila actual hacia abajo. Esto asegura que los divisores en las operaciones de eliminación sean lo más grandes posibles, lo que reduce el riesgo de errores de redondeo, especialmente cuando se trabaja con números muy pequeños o en sistemas mal condicionados.

Con respecto al Intercambio de Filas: Al realizar el pivoteo, se intercambian filas para llevar el mayor valor al lugar del pivote. Esto puede cambiar significativamente el comportamiento del sistema, permitiendo que el algoritmo sea más robusto frente a errores.

Y la Matriz Resultante: Como resultado de aplicar el pivoteo parcial, la matriz resultante después de la eliminación puede tener una estructura diferente a la que se obtendría sin pivoteo. Esto hace que la solución sea más precisa y confiable.

(b) Usar Eliminación Gaussiana con pivoteo parcial para resolver sistemas de varios tamaños (al menos 5) con vectores $b$ elegidos por cualquier criterio. Describir como se comporta la condición de la matriz.

Comportamiento de la condición de la matriz:

1.- Número de condición: el número de condición de una matrizz $A$ se define como $k(A)=||A||||A^-1||.$ que indica qué tanto cambia la solución del sistema en $A$ o en el vector $b.$ Un número de condición grande indica que la matriz está mal condicionada lo que puede llevar a cambios significativamente grandes en la solución.

2.- Ejecución: en los sistemas resueltos con distintos tamaños elegidos aleatoriamente, el número deo cndición cambia. Cuando este número es bajoel sistema está bien condicionado y las soluciones son robustas. Y si el número es alto, como ya mencionamos anteriormente, el sistema está mal condicionado y las soluciones pueden ser inexactas.

3.- Soluciones: la Eliminación Gaussiana con pivoteo parcial nos da soluciones más precisas a comparación con el método sin pivoteo.


(c) Escribir una rutina que factorice la matriz ($LU$) con pivoteo total.

Factorización $LU$ con pivoteo total: descompone una matriz $A$ en el producto de una matriz de permutación $P$, una matriz triangular inferior $L$ y una matriz trianfular superior $U$. Así reduce el riesgo de obtener errores de redondeo.

Rutina:

1.- Intercambio de filas y columnas: como el pivoteo total intercambia filas y columnas asegura que se estén usand oel máximo de elementos en cada paso de la eliminación.

2.- Matriz de permutación: la matriz $P$ realiza estos intercambios, y se actualiza en cada paso. Esto hace que las soluciones se mantengan dentro de un intervalo de precisión estable.

3.- Descomposición: la rutina realiza la descomposión de la matriz $A$ en $L$ y $U$ de tal manera que $PA=LU,$ donde $P$ es la matriz de permutación.

4.- Implementación: la implementación de la rutina se basa en buscar el máximo elemento en la submatriz y realizar los intercambios necesarios.



# 21.-
Usar la Eliminación Gaussiana sin pivoteo para resolver el sistema:

$\begin{equation}
\begin{bmatrix}
\epsilon & 1  \\
1 & 1  
\end{bmatrix}
\end{equation}$ $\begin{equation}
\begin{bmatrix}
x_1 \\
x_2   
\end{bmatrix}
\end{equation}$ $\begin{equation}
\begin{bmatrix}
1+\epsilon \\
2   
\end{bmatrix}
\end{equation}$

para $\epsilon= 10^{-2k},$ con $k=1,\cdots,10$. Lasolución exacta es $x=[1\space 1]^T$, ¿cómo se comporta la solución conforme $\epsilon$ decrece?

In [2]:
# Solución para la pregunta 21
#Eliminación Gaussiana sin pivoteo
#Valores de epsilon
import numpy as np
k_values = range(1, 11)
epsilon_values = [10**(-2 * k) for k in k_values]

#Función para eliminación Gaussiana sin pivoteo
def gaussian_elimination(A, b):
    n = len(b)
    #Eliminación hacia adelante
    for i in range(n):
        for j in range(i+1, n):
            factor = A[j][i] / A[i][i]
            for k in range(i, n):
                A[j][k] -= factor * A[i][k]
            b[j] -= factor * b[i]
    #Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = b[i]
        for j in range(i+1, n):
            x[i] -= A[i][j] * x[j]
        x[i] /= A[i][i]
    return x

#Solución exacta
exact_solution = np.array([1, 1])

#Resolver el sistema para cada epsilon y comparar con la solución exacta
print("Problema 21: Solución y error para diferentes valores de epsilon")
for epsilon in epsilon_values:
    A = np.array([[epsilon, 1], [1, 1]], dtype=float)
    b = np.array([1 + epsilon, 2], dtype=float)
    solution = gaussian_elimination(A.copy(), b.copy())
    error = np.linalg.norm(solution - exact_solution)
    print(f"ε = {epsilon:.1e} -> solución: {solution}, error: {error:.2e}")
print("\n")

Problema 21: Solución y error para diferentes valores de epsilon
ε = 1.0e-02 -> solución: [1. 1.], error: 8.88e-16
ε = 1.0e-04 -> solución: [1. 1.], error: 1.10e-13
ε = 1.0e-06 -> solución: [1. 1.], error: 2.88e-11
ε = 1.0e-08 -> solución: [0.99999999 1.        ], error: 6.08e-09
ε = 1.0e-10 -> solución: [1.00000008 1.        ], error: 8.27e-08
ε = 1.0e-12 -> solución: [0.99986686 1.        ], error: 1.33e-04
ε = 1.0e-14 -> solución: [0.99920072 1.        ], error: 7.99e-04
ε = 1.0e-16 -> solución: [2.22044605 1.        ], error: 1.22e+00
ε = 1.0e-18 -> solución: [0. 1.], error: 1.00e+00
ε = 1.0e-20 -> solución: [0. 1.], error: 1.00e+00




# 22.-
Sea el sistema $A\bar{x}=\bar{b}$ dado por

$A=
\begin{equation}
\begin{bmatrix}
9 & -4 & 1 & 0 & \cdots & \cdots & 0\\
-4 & 6 & -4 & 1 & \ddots & &  \vdots\\
1 & -4 & 6 & -4 & 1 & \ddots & \vdots \\
0 & \ddots & \ddots & \ddots & \ddots & \ddots & 0\\
\vdots & \ddots & 1 & -4 & 6 & -4 & 1\\
\vdots & & \ddots & 1 & -4 & 5 & -2\\
0 & \cdots & \cdots & 0 & 1 & -2 & 1
\end{bmatrix}
\end{equation}$

tomando $\bar{b}=[1,1,\cdots,1]^T.$ Para $n=100$ resolver por:

(a) Factorización $LU$

(b) Crear una rutina (tipo banda) para la estructura de la matriz y resolver. Comparar y comentar $22a$ y $22b$.

(c) Verificar que la matriz $A$ tiene una factorización de la forma $A=RR^T$ donde $R$ es una matriz triangular superior de la forma

$\begin{equation}
\begin{bmatrix}
2 & -2 & 1 & 0 & \cdots & 0\\
0 & 1 & -2 & 1 & \ddots & \vdots\\
\vdots & \ddots & \ddots & \ddots & \ddots & 0\\
\vdots & &  \ddots & 1 & -2 & 1 \\
\vdots & & &  \ddots & 1 & -2 \\
0 & \cdots & \cdots & \cdots & 0 & 1
\end{bmatrix}
\end{equation}$


Crear una rutina con la factorización $RR^T$ . Para $n=100$ resolver el sistema.

Comparar y resolver $22a, 22b$ y $22c$.

In [ ]:
# Solución para la pregunta 22.-(a)

import numpy as np
from scipy.linalg import lu_factor, lu_solve

# Tamaño del sistema
n = 100

# Definir la matriz A como tridiagonal
A = np.zeros((n, n))

# Llenar la matriz con los valores dados
A[0, 0] = 9
A[0, 1] = -4
for i in range(1, n-1):
    A[i, i-1] = -4
    A[i, i] = 6
    A[i, i+1] = -4
A[n-1, n-2] = -4
A[n-1, n-1] = 1

# Definir el vector b con todos sus elementos iguales a 1
b = np.ones(n)

# Factorización LU de A
lu, piv = lu_factor(A)

# Resolver el sistema A*x = b usando la factorización LU
x = lu_solve((lu, piv), b)

# Imprimir la solución
print("La solución del sistema A*x = b es:")
print(x)



La solución del sistema A*x = b es:
[ 1.33520222e-01  5.04204995e-02 -3.07889473e-01 -7.62254709e-01
 -1.08549259e+00 -1.11598418e+00 -8.38483675e-01 -3.91741336e-01
  8.71671492e-04  1.43048843e-01 -3.62984074e-02 -4.47496454e-01
 -8.84946273e-01 -1.12992296e+00 -1.05993816e+00 -7.09984285e-01
 -2.55038267e-01  7.74268849e-02  1.21178594e-01 -1.45658994e-01
 -5.89667085e-01 -9.88841633e-01 -1.14359537e+00 -9.76551415e-01
 -5.71231757e-01 -1.30296220e-01  1.25787426e-01  6.89773597e-02
 -2.72321387e-01 -7.27459440e-01 -1.06886777e+00 -1.12584222e+00
 -8.69895557e-01 -4.29001115e-01 -2.36061163e-02  1.43591941e-01
 -1.10059725e-02 -4.10100900e-01 -8.54145377e-01 -1.12111717e+00
 -1.07753037e+00 -7.45178392e-01 -2.90237216e-01  5.98225677e-02
  1.29971068e-01 -1.14865966e-01 -5.52270017e-01 -9.63539059e-01
 -1.14303857e+00 -1.00101880e+00 -6.08489626e-01 -1.61715640e-01
  1.15916165e-01  8.55898885e-02 -2.37531333e-01 -6.91886887e-01
 -1.05029900e+00 -1.13356161e+00 -9.00043417e-01 -4.66

In [ ]:
# Solución para la pregunta 22.- (b)

import numpy as np
from scipy.linalg import solve_banded

# Tamaño del sistema
n = 100

# Definir el vector b con todos sus elementos iguales a 1
b = np.ones(n)

'''-Definir la matriz banda en forma compacta
   -Matriz A tiene 4 diagonales:
        (1 subdiagonal,
         2 superdiagonales,
         y la diagonal principal)
   -Usaremos la forma (l,u), donde l es el número de subdiagonales y u es el número de superdiagonales
'''

# Diagonal superior (1)
diag_sup1 = np.zeros(n-1)
diag_sup1[:] = -4

# Diagonal superior (2)
diag_sup2 = np.zeros(n-2)
diag_sup2[:] = 1

# Diagonal principal
diag_prin = np.zeros(n)
diag_prin[0] = 9
diag_prin[1:-1] = 6
diag_prin[-1] = 1

# Diagonal inferior (1)
diag_inf1 = np.zeros(n-1)
diag_inf1[:] = -4

# Diagonal inferior (2)
diag_inf2 = np.zeros(n-2)
diag_inf2[:] = 1

# Matriz banda en formato (3 filas: 2 diagonales superiores, diagonal principal, 2 diagonales inferiores)
ab = np.zeros((5, n))
ab[0, 2:] = diag_sup2  # segunda diagonal superior
ab[1, 1:] = diag_sup1  # primera diagonal superior
ab[2, :] = diag_prin   # diagonal principal
ab[3, :-1] = diag_inf1  # primera diagonal inferior
ab[4, :-2] = diag_inf2  # segunda diagonal inferior

# Resolver el sistema usando solve_banded
x = solve_banded((2, 2), ab, b)

# Imprimir la solución
print("La solución del sistema A*x = b es:")
print(x)


La solución del sistema A*x = b es:
[ 2.11356759e+02  1.21840073e+03  2.97239207e+03  5.42559097e+03
  8.53125759e+03  1.22436521e+04  1.65180347e+04  2.13106655e+04
  2.65788047e+04  3.22807125e+04  3.83756491e+04  4.48238745e+04
  5.15866491e+04  5.86262329e+04  6.59058862e+04  7.33898691e+04
  8.10434417e+04  8.88328644e+04  9.67253971e+04  1.04689300e+05
  1.12693834e+05  1.20709258e+05  1.28706833e+05  1.36658819e+05
  1.44538476e+05  1.52320064e+05  1.59978844e+05  1.67491075e+05
  1.74834019e+05  1.81985934e+05  1.88926082e+05  1.95634722e+05
  2.02093114e+05  2.08283519e+05  2.14189197e+05  2.19794408e+05
  2.25084412e+05  2.30045470e+05  2.34664841e+05  2.38930786e+05
  2.42832565e+05  2.46360438e+05  2.49505665e+05  2.52260506e+05
  2.54618222e+05  2.56573073e+05  2.58120319e+05  2.59256220e+05
  2.59978036e+05  2.60284027e+05  2.60173455e+05  2.59646578e+05
  2.58704656e+05  2.57349951e+05  2.55585723e+05  2.53416230e+05
  2.50846735e+05  2.47883496e+05  2.44533774e+05  2.40

### Compara y comentar 22(a) y 22(b):

La ventaja pricicpal del método $LU$ es que puede ser reutilizado para resolver el  mismo sistema con diferentes vetores $b$, lo que lo hace más eficiente.

La resolución usando matriz tipo banda solo almacena y procesa las entradas no nulas cercanas a la diagonal principal. Esto permite reducir la complejidad del problema al igual que el número de operaciones.

Para una matriz como la del problema 22 que es tridiagonal con algunas bandas diagonales adicionales. el método de banda es mucho más eficiente, tanto en memoria como en tiempo computacional. Estamos evitando operaciones innecesarias.

Precisión:

Ambos métodos ofrecen resultados similares en cuanto a precisión numérica. Pero el método de banda es un poco más estable pues evita errores acumulados en las permutaciones y eliminaciones en las entradas nulas de  la matriz.

Conclusión:

El método de banda es la mejor opción para este caso.

In [ ]:
# Solución para la pregunta 22.- (c)

import numpy as np

# Paso 1: Crear la matriz A con la estructura dada
def crear_matriz_A(n):
    A = np.zeros((n, n))
    for i in range(n):
        if i == 0:
            A[i, i] = 9
            A[i, i + 1] = -4
            A[i, i + 2] = 1
        elif i == 1:
            A[i, i - 1] = -4
            A[i, i] = 6
            A[i, i + 1] = -4
            A[i, i + 2] = 1
        elif i == n - 2:
            A[i, i - 2] = 1
            A[i, i - 1] = -4
            A[i, i] = 6
            A[i, i + 1] = -4
        elif i == n - 1:
            A[i, i - 2] = 0
            A[i, i - 1] = 1
            A[i, i] = 1
        else:
            A[i, i - 2] = 1
            A[i, i - 1] = -4
            A[i, i] = 6
            A[i, i + 1] = -4
            A[i, i + 2] = 1
    return A

# Paso 2: Crear la matriz R
def crear_matriz_R(n):
    R = np.zeros((n, n))
    for i in range(n):
        if i == 0:
            R[i, i] = 2
            R[i, i + 1] = -2
            R[i, i + 2] = 1
        elif i == 1:
            R[i, i] = 1
            R[i, i + 1] = -2
            R[i, i + 2] = 1
        elif i == n - 2:
            R[i, i] = 1
            R[i, i + 1] = -2
        elif i == n - 1:
            R[i, i] = 1
        else:
            R[i, i] = 1
            R[i, i + 1] = -2
            R[i, i + 2] = 1
    return R

# Paso 3: Verificar la factorización A = RR^T
def verificar_factorizacion(A, R):
    A_reconstruida = np.dot(R, R.T)
    return np.allclose(A, A_reconstruida)

# Definir n
n = 100

# Crear la matriz A
A = crear_matriz_A(n)

# Crear la matriz R
R = crear_matriz_R(n)

# Verificar la factorización A = RR^T
es_correcta = verificar_factorizacion(A, R)

# Imprimir el resultado
if es_correcta:
    print("La factorización A = RR^T es correcta.")
else:
    print("La factorización A = RR^T NO es correcta.")


La factorización A = RR^T NO es correcta.


### Comparar
$22(a),22(b)$ y $22(c)$:

* La factorización $LU$ (inciso (a)) es adecuada para resolver sistemas con cualquier matriz, pero no explota la estructura de banda, lo que puede resultar en un costo computacional elevado.

* La rutina de banda (inciso b) es la mejor opción cuando la matriz tiene una estructura clara, como en este caso. Este enfoque mejorar la eficiencia.

* La factorización $RR^T$ sería preferible si $A$ fuera una matriz simétrica y definida positiva. Sin embargo, si la factorización falla, este método no es viable, lo que limita su aplicabilidad en comparación con los otros métodos. Justo lo que ocurrió en este caso.



#23.-
Programar la Factorización de Cholesky dada por:

(a) $A=LL^T$

(b) $A=\hat{L} \hat{D} \hat{L}^T$,
 $\hat{L}$  triangular y $\hat{D}$ diagonal.

In [3]:
# Solución para la pregunta 23
# Factorización de Cholesky
#Factorización Cholesky A = LL^T

def cholesky_LLT(A):
    n = A.shape[0]
    L = np.zeros_like(A)
    for i in range(n):
        for j in range(i+1):
            sum_k = np.sum(L[i, :j] * L[j, :j])
            if i == j:
                L[i, j] = np.sqrt(A[i, i] - sum_k)  #Elementos diagonales
            else:
                L[i, j] = (A[i, j] - sum_k) / L[j, j]  #Elementos no diagonales
    return L

#Factorización Cholesky A = L D L^T
def cholesky_LDLT(A):
    n = A.shape[0]
    L = np.zeros_like(A)
    D = np.zeros_like(A)
    for i in range(n):
        for j in range(i):
            sum_k = np.sum(L[i, :j] * D[j, j] * L[j, :j])
            L[i, j] = (A[i, j] - sum_k) / D[j, j]  #Elementos no diagonales
        sum_k = np.sum(L[i, :i]**2 * D[:i, :i].diagonal())
        D[i, i] = A[i, i] - sum_k  #Elementos diagonales en D
        L[i, i] = 1  #Elementos unitarios en la diagonal de L
    return L, D

print("Problema 23: Factorización de Cholesky (LL^T y LDL^T)\n")


Problema 23: Factorización de Cholesky (LL^T y LDL^T)



24.-
Encontrar la Factorización de Cholesky de $A$ para las siguientes matrices:

$
A=\begin{equation}
\begin{bmatrix}
2 & -1 & 0\\
-1 & 2 & -1\\
0 & -1 & 2
\end{bmatrix}
\end{equation}
$ ;
$B=\begin{equation}
\begin{bmatrix}
4 & 1 & 1  & 1\\
1 & 3 & -1 & 1\\
1 & -1 & 2 & 0\\
1 & 1 & 0 & 2
\end{bmatrix}
\end{equation}
$

$
C=\begin{equation}
\begin{bmatrix}
4 & 1 & -1 & 0\\
1 & 3 & -1 & 0\\
-1 & -1 & 5 & 2\\
0 & 0 & 2 & 4
\end{bmatrix}
\end{equation}
$;
$
D=\begin{equation}
\begin{bmatrix}
6 & 2 & 1 & -1\\
2 & 4 & 1 & 0\\
1 & 1 & 4 & -1\\
-1 & 0 & -1 & 3
\end{bmatrix}
\end{equation}
$

Utilizando:

(a) $A=LL^T$

(b) $A=\hat{L} \hat{D} \hat{L}^T$

In [4]:
# Solución para la pregunta 24

A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]], dtype=float)
B = np.array([[4, 1, 1], [1, 3, -1], [1, -1, 2]], dtype=float)
C = np.array([[4, 1, -1, 0], [1, 3, -1, 0], [-1, -1, 5, 2], [0, 0, 2, 4]], dtype=float)
D = np.array([[6, 2, 1, -1], [2, 4, 1, 0], [1, 1, 4, -1], [-1, 0, -1, 3]], dtype=float)

#Aplicar factorización de Cholesky a cada matriz y mostrar resultados
for matrix, name in zip([A, B, C, D], ['A', 'B', 'C', 'D']):
    #Forma LL^T
    L = cholesky_LLT(matrix)
    print(f"Matriz {name} (A = LL^T):\nL:\n{L}\n")

    #Forma LDL^T
    L, D_diag = cholesky_LDLT(matrix)
    print(f"Matriz {name} (A = LDL^T):\nL:\n{L}\nD:\n{D_diag}\n")


Matriz A (A = LL^T):
L:
[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]

Matriz A (A = LDL^T):
L:
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
D:
[[2.         0.         0.        ]
 [0.         1.5        0.        ]
 [0.         0.         1.33333333]]

Matriz B (A = LL^T):
L:
[[ 2.          0.          0.        ]
 [ 0.5         1.6583124   0.        ]
 [ 0.5        -0.75377836  1.08711461]]

Matriz B (A = LDL^T):
L:
[[ 1.          0.          0.        ]
 [ 0.25        1.          0.        ]
 [ 0.25       -0.42613636  1.        ]]
D:
[[4.         0.         0.        ]
 [0.         2.75       0.        ]
 [0.         0.         1.25062145]]

Matriz C (A = LL^T):
L:
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [-0.5        -0.45226702  2.13200716  0.        ]
 [ 0.          0.        