<a href="https://colab.research.google.com/github/lauravazqx/Analisis-Numerico/blob/main/Proyecto1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyecto 1.

*   Galicia Luna Luis
*   Salvador Vázquez Laura Teresa


## Ejercicio 1: Con la estructura de datos *list* realice los siguientes programas:


* Programe la multiplicación de matrices, recuerde que no necesariamente tienen
por qué ser cuadradas, por lo que deberá validar que se pueda realizar la multiplicación.




In [1]:
def multiplicar_matrices(A, B):
    #Verificar si la multiplicacion es posible
    if len(A[0]) != len(B):
        raise ValueError("Las matrices no se pueden multiplicar")

    #Crear una matriz resultado inicializada con ceros
    resultado = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    #Realizar la multiplicacion
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                resultado[i][j] += A[i][k] * B[k][j]

    return resultado


In [8]:
#Prueba 1: Multiplicacion de matrices
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
resultado_multiplicacion = multiplicar_matrices(A, B)

print("Resultado de la multiplicacion de matrices A*B:")
for fila in resultado_multiplicacion:
    print(fila)

Resultado de la multiplicacion de matrices A*B:
[19, 22]
[43, 50]




*   Programe la multiplicación de matrices por bloques.




In [2]:
def multiplicacion_bloques(A, B, block_size):
    n = len(A)  #se asume que A y B son matrices cuadradas de tamaño n x n
    C = [[0 for _ in range(n)] for _ in range(n)]  #Inicia la matriz resultado C

    #bloques de tamaño block_size
    for i in range(0, n, block_size):
        for j in range(0, n, block_size):
            for k in range(0, n, block_size):

                #Los bucles internos realizan la multiplicación de los bloques
                for ii in range(i, min(i + block_size, n)):
                    for jj in range(j, min(j + block_size, n)):
                        for kk in range(k, min(k + block_size, n)):
                            #Multiplica y suma
                            C[ii][jj] += A[ii][kk] * B[kk][jj]

    return C



In [9]:
#Prueba 2: Multiplicacion de matrices por bloques (bloque de 1x1)
resultado_multiplicacion_bloques = multiplicacion_bloques(A, B, 1)

print("\nResultado de la multiplicacion de matrices por bloques (1x1):")
for fila in resultado_multiplicacion_bloques:
    print(fila)


Resultado de la multiplicacion de matrices por bloques (1x1):
[19, 22]
[43, 50]




*   Haga un programa que realice la transpuesta de una matriz.



In [3]:
def transponer_matriz(A):
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

In [10]:
#Prueba 3: Transpuesta de una matriz
transpuesta = transponer_matriz(A)

print("\nTranspuesta de la matriz A:")
for fila in transpuesta:
    print(fila)


Transpuesta de la matriz A:
[1, 3]
[2, 4]




*   Haga un programa que realice la potencia de una matriz.



In [20]:
def potencia_matriz(A, n):
    """
    - Se utiliza la matriz identidad como punto de partida para la realizar la potencia.
    - Si n es 0, el resultado es la matriz identidad.
    - Se asume que A es una matriz cuadrada (el número de filas es igual al número de columnas).
    """

    # Verifica que la matriz A sea cuadrada
    if len(A) != len(A[0]):
        raise ValueError("La matriz debe ser cuadrada.")

    # Inicializa el resultado como la matriz identidad del mismo tamaño que A
    # La matriz identidad tiene 1's en la diagonal principal y 0's en las demás posiciones
    resultado = [[1 if i == j else 0 for j in range(len(A))] for i in range(len(A))]

    # Calcula la potencia de la matriz A multiplicando repetidamente el resultado por A
    for _ in range(n):
        resultado = multiplicar_matrices(resultado, A)

    # Retorna la matriz resultado, que es A elevado a la potencia n
    return resultado


In [21]:
#Prueba 4: Potencia de una matriz
A = [[3, 2],
    [1, 3]]
n = 5  # Potencia a la que quieres elevar la matriz

resultado = potencia_matriz(A, n)
print("Resultado de A^{}:".format(n))
for fila in resultado:
    print(fila)

Resultado de A^5:
[843, 1178]
[589, 843]




*   Desarrollar un programa que calcule el producto cruz entre dos vectores tridimensionales.



In [25]:
def ProductoCruz(v1, v2):
    """
    Calcula el producto cruz entre dos vectores tridimensionales.

    Parámetros:
    v1 (list of float/int): Primer vector tridimensional, representado como una lista de 3 elementos.
    v2 (list of float/int): Segundo vector tridimensional, representado como una lista de 3 elementos.

    Retorna:
    list of float/int: El vector resultante del producto cruz, también representado como una lista de 3 elementos.

    Excepciones:
    ValueError: Si los vectores no son tridimensionales.
    """

    # Verifica que ambos vectores tengan 3 componentes
    if len(v1) != 3 or len(v2) != 3:
        raise ValueError("Ambos vectores deben ser tridimensionales (tener 3 componentes).")

    # Cálculo del producto cruz
    cruz =  [v1[1] * v2[2] - v1[2] * v2[1],  # Componente en x
             v1[2] * v2[0] - v1[0] * v2[2],  # Componente en y
             v1[0] * v2[1] - v1[1] * v2[0]]  # Componente en z

    return cruz


In [26]:
#Prueba 5: Producto cruz entre dos vectores tridimensionales
v1 = [2, 7, 3]
v2 = [6, 9, 1]

resultado = ProductoCruz(v1, v2)

print("El producto cruz entre v1 y v2 es:", resultado)

El producto cruz entre v1 y v2 es: [-20, 16, -24]




*   Crear un programa que aplique una rotación de un vector bidimensional mediante una matriz de rotación.



In [4]:
import math
import numpy as np

def rotar_vector_2D(v, angulo):
    #Matriz de rotacion
    cos_theta = math.cos(angulo)
    sin_theta = math.sin(angulo)
    matriz_rotacion = [[cos_theta, -sin_theta], [sin_theta, cos_theta]]

    #Aplicar la rotacion
    x = matriz_rotacion[0][0] * v[0] + matriz_rotacion[0][1] * v[1]
    y = matriz_rotacion[1][0] * v[0] + matriz_rotacion[1][1] * v[1]

    return [x, y]


In [11]:
#Prueba 6: Rotacion de un vector 2D
v2D = [1, 0]
angulo = math.pi / 4  #45 grados
vector_rotado_2D = rotar_vector_2D(v2D, angulo)

print(f"\nVector 2D original: {v2D}")
print(f"Vector 2D rotado 45 grados: {vector_rotado_2D}")


Vector 2D original: [1, 0]
Vector 2D rotado 45 grados: [0.7071067811865476, 0.7071067811865475]




*   Crear un programa que aplique una rotación de un vector tridimensional mediante una matriz de rotación.



In [5]:
def rotar_vector_3D(v, angulo, eje):
    #Matrices de rotacion para cada eje
    if eje == 'x':
        matriz_rotacion = np.array([[1, 0, 0],
                                    [0, np.cos(angulo), -np.sin(angulo)],
                                    [0, np.sin(angulo), np.cos(angulo)]])
    elif eje == 'y':
        matriz_rotacion = np.array([[np.cos(angulo), 0, np.sin(angulo)],
                                    [0, 1, 0],
                                    [-np.sin(angulo), 0, np.cos(angulo)]])
    elif eje == 'z':
        matriz_rotacion = np.array([[np.cos(angulo), -np.sin(angulo), 0],
                                    [np.sin(angulo), np.cos(angulo), 0],
                                    [0, 0, 1]])
    else:
        raise ValueError("es eje no es valido Debe ser x, y o z")

    return np.dot(matriz_rotacion, v)

In [12]:
#Prueba 7: Rotacion de un vector 3D alrededor del eje Z
v3D = [1, 0, 0]
vector_rotado_3D = rotar_vector_3D(v3D, angulo, 'z')

print(f"\nVector 3D original: {v3D}")
print(f"Vector 3D rotado 45 grados alrededor del eje Z: {vector_rotado_3D}")


Vector 3D original: [1, 0, 0]
Vector 3D rotado 45 grados alrededor del eje Z: [0.70710678 0.70710678 0.        ]




*   Calcule la norma 1,

$
||A||_1 = \max_{1 \leq j \leq n} \sum_{i=1}^{m} |a_{ij}|
$




In [34]:
def Norma_1(A):
    """
    Calcula la norma 1 de una matriz A.

    La norma 1 es el máximo de la suma de los valores absolutos de los elementos
    en cada columna de la matriz.

    Parámetros:
    A (list of list of float/int): La matriz para la que se quiere calcular la norma 1.

    Retorna:
    float: El valor de la norma 1 de la matriz A.

    Excepciones:
    ValueError: Si la matriz está vacía o las filas tienen longitudes diferentes.
    """

    # Verifica si la matriz está vacía
    if len(A) == 0 or len(A[0]) == 0:
        raise ValueError("La matriz no debe estar vacía.")

    # Verifica que todas las filas tengan la misma longitud
    n_columnas = len(A[0])
    if not all(len(fila) == n_columnas for fila in A):
        raise ValueError("Todas las filas deben tener la misma longitud.")

    # Calcula la norma 1 (máxima suma de valores absolutos de cada columna)
    max_suma_columnas = max(
        sum(abs(A[i][j]) for i in range(len(A))) for j in range(n_columnas)
    )

    return max_suma_columnas





In [38]:
#Prueba 8: Calcule la norma 1
A = [[1, 3, 4], [9, 8, 6], [7, -5, 0]]

resultado = Norma_1(A)
print("La norma 1 de la matriz A es:", resultado)

La norma 1 de la matriz A es: 17




*   Calcule la norma infinito,

$
||A||_{\infty} = \max_{1 \leq i \leq m} \sum_{j=1}^{n} |a_{ij}|
$




In [27]:
def NormaInfinito(A):
    """
    Calcula la norma infinito de una matriz A.

    La norma infinito se define como el máximo de la suma de los valores absolutos de los elementos
    en cada fila de la matriz.

    Parámetros:
    A (list of list of float/int): La matriz para la que se quiere calcular la norma infinito.

    Retorna:
    float: El valor de la norma infinito de la matriz A.

    Excepciones:
    ValueError: Si la matriz está vacía o las filas tienen longitudes diferentes.
    """

    # Verifica si la matriz está vacía
    if len(A) == 0 or len(A[0]) == 0:
        raise ValueError("La matriz no debe estar vacía.")

    # Verifica que todas las filas tengan la misma longitud
    if not all(len(fila) == len(A[0]) for fila in A):
        raise ValueError("Todas las filas deben tener la misma longitud.")

    # Calcula la norma infinito
    max_suma_filas = max(sum(abs(aij) for aij in fila) for fila in A)

    return max_suma_filas




In [29]:
#Prueba 9: Calcule la norma infinito
A = [[2, -4, 7],
    [-3, 5, -1],
    [6, -8, 1]]

resultado = NormaInfinito(A)
print("La norma infinito de la matriz A es:", resultado)

La norma infinito de la matriz A es: 15




*   Calcule la norma 2,

$
||A||_2 = \sqrt{\sum_{j=1}^{n} a_{ij}^2}
$




In [39]:
import math

def norma_2(A):
    """
    Calcula la norma 2 (norma Euclidiana) de cada fila de la matriz A.

    La norma 2 de una fila es la raíz cuadrada de la suma de los cuadrados
    de los elementos en esa fila.

    Parámetros:
    A (list of list of float/int): La matriz para la que se quieren calcular las normas 2 de las filas.

    Retorna:
    list of float: Una lista con la norma 2 de cada fila de la matriz A.

    Excepciones:
    ValueError: Si la matriz está vacía o las filas tienen longitudes diferentes.
    """

    # Verifica si la matriz está vacía
    if len(A) == 0 or len(A[0]) == 0:
        raise ValueError("La matriz no debe estar vacía.")

    # Verifica que todas las filas tengan la misma longitud
    if not all(len(fila) == len(A[0]) for fila in A):
        raise ValueError("Todas las filas deben tener la misma longitud.")

    # Calcula la norma 2 para cada fila
    normas_2 = []
    for fila in A:
        norma_2 = math.sqrt(sum(aij ** 2 for aij in fila))  # Suma de los cuadrados y luego raíz cuadrada
        normas_2.append(norma_2)

    return normas_2
"""
La función recibe una matriz 𝐴 y calcula la norma 2 de cada una de sus filas.
Primero, verifica que la matriz no esté vacía y que todas las filas tengan la misma longitud.
Luego, para cada fila, calcula la suma de los cuadrados de sus elementos y después toma la raíz cuadrada de esa suma, lo que corresponde a la norma 2.
Finalmente, devuelve una lista con las normas 2 de todas las filas.
"""


In [41]:
#Prueba 2: Calcule la norma 2
A = [[0, 3, 7], [-5, -9, 4], [2, -7, 9]]

resultado = norma_2(A)
print("La norma 2 de cada fila de la matriz A es:", resultado)

La norma 2 de cada fila de la matriz A es: [7.615773105863909, 11.045361017187261, 11.575836902790225]


## Ejercicio 2: con la estructura de datos *array* realice los siguientes programas:



*   Realice un programa que resuelva un sistema de dos bandas, considere
que una de las bandas puede ser la diagonal superior o inferior, pero la
principal siempre está presente, por lo que su programa debe ser capaz
de resolver ambos casos.



In [46]:
import numpy as np

def resolver_sistema_dos_bandas(A, b, banda='superior'):
    """
    Resuelve un sistema de ecuaciones lineales Ax = b para una matriz A de dos bandas.

    Parámetros:
    A (np.array): Matriz cuadrada de dos bandas de tamaño (n, n). Tiene la diagonal principal y una diagonal adicional
                  que puede estar por encima o por debajo de la principal.
    b (np.array): Vector del lado derecho de tamaño (n,).
    banda (str): Indica si la banda adicional está por encima ('superior') o por debajo ('inferior') de la diagonal principal.
                 Valor por defecto es 'superior'.

    Retorna:
    np.array: Solución del sistema de ecuaciones x, tal que Ax = b.

    Excepciones:
    ValueError: Si el parámetro 'banda' es inválido o si hay un cero en la diagonal principal.
    """

    n = len(b)  # Longitud del vector (también es el tamaño de la matriz A)
    x = np.zeros_like(b, dtype=float)  # Vector solución inicializado en ceros (float)

    # Verifica si hay ceros en la diagonal principal
    if np.any(np.diag(A) == 0):
        raise ValueError("La matriz contiene un cero en la diagonal principal, lo que impide la resolución del sistema.")

    if banda == 'superior':
        # Algoritmo de eliminación hacia atrás para matriz con banda superior
        for i in range(n - 1, -1, -1):
            if i < n - 1:
                b[i] -= A[i, i + 1] * x[i + 1]  # Resta el término de la banda superior
            x[i] = b[i] / A[i, i]  # División por la diagonal principal
    elif banda == 'inferior':
        # Algoritmo de sustitución hacia adelante para matriz con banda inferior
        for i in range(n):
            if i > 0:
                b[i] -= A[i, i - 1] * x[i - 1]  # Resta el término de la banda inferior
            x[i] = b[i] / A[i, i]  # División por la diagonal principal
    else:
        raise ValueError("El parámetro 'banda' debe ser 'superior' o 'inferior'.")

    return x






In [48]:
#Prueba 1: Calcule el sistema de dos bandas
# Matriz A con banda superior
A_superior = np.array([
    [2.0, -1.0, 0.0],
    [0.0, 1.0, -2.0],
    [0.0, 0.0, 2.0]])


# Matriz A con banda inferior
A_inferior = np.array([
    [4.0, 0.0, 0.0],
    [-1.0, 9.0, 0.0],
    [8.0, -2.0, 2.0]])


# Vector del lado derecho
b = np.array([3.0, 5.0, -4.0])

# Resolviendo para la matriz con banda superior
try:
    x_superior = resolver_sistema_dos_bandas(A_superior, b.copy(), banda='superior')
    print("Solución para la banda superior:", x_superior)
except ValueError as e:
    print("Error:", e)

# Resolviendo para la matriz con banda inferior
try:
    x_inferior = resolver_sistema_dos_bandas(A_inferior, b.copy(), banda='inferior')
    print("Solución para la banda inferior:", x_inferior)
except ValueError as e:
    print("Error:", e)


Solución para la banda superior: [ 2.  1. -2.]
Solución para la banda inferior: [ 0.75        0.63888889 -1.36111111]




*   Modifique el algoritmo de Thomas, de manera que en lugar de resolver
el sistema con una sustitución hacia atrás, se haga una sustitución hacia
delante.



In [50]:
import numpy as np
def resolver_sistema_dos_bandas(A, b):
    n = len(b)
    x = np.zeros_like(b)

    #Eliminacion hacia adelante como algoritmo de Thomas
    for i in range(1, n):
        factor = A[i][i-1] / A[i-1][i-1]
        A[i][i] -= factor * A[i-1][i]
        b[i] -= factor * b[i-1]

    #Sust hacia atras
    x[-1] = b[-1] / A[-1][-1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - A[i][i+1] * x[i+1]) / A[i][i]

    return x

#matriz tridiagonal
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]], dtype=float)
b = np.array([1, 0, 1], dtype=float)

#Se resuelve el sistema
solucion = resolver_sistema_dos_bandas(A.copy(), b.copy())




In [51]:
print("Sistema de ecuaciones:")
print("Matriz A:")
print(A)
print("Vector b:")
print(b)

print("\nSolución del sistema (algoritmo de Thomas modificado):")
print(solucion)

Sistema de ecuaciones:
Matriz A:
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
Vector b:
[1. 0. 1.]

Solución del sistema (algoritmo de Thomas modificado):
[1. 1. 1.]
